name: deploy

on:
  push:
    branches:
      - main
      - feat/migrate-to-slinkity # todo: remove once deploy to remote main is verified and before merging to repo main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: install
        uses: bahmutov/npm-install@v1
        with:
          node-version: 16
        env:
          NODE_ENV: production
      - run: npm run build
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
