on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile --silent
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/filoxo/filoxo.github.io.git
          yarn deploy -u "Carlos Filoteo <c.filoteo12@gmail.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
