name: Deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: yarn
    - name: Configure git
      run: git config user.name "Carlos Filoteo" && git config user.email "c.filoteo12@gmail.com"
    - name: Deploy to Github pages
      run: yarn deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
